version: "3.3"

services: 
    db:
        image: postgres:10
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=1234test
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - db 